name: CI/CD Pipeline new

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker Image
      run: |
        docker build -t myapp:latest .

    - name: Transfer Files to AWS EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_SSH_KEY }}
        source: "."
        target: "/home/ubuntu/myapp"

    - name: Deploy on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /home/ubuntu/myapp
          docker-compose down
          docker-compose up --build -d
